### ISSUE TITLE
Shaking Video on Android

### ISSUE THREAD

**Issue by calinvasileandrei** [flutterwtf/VR-Player#37]
Hello everyone, I'm using this library for one of my projects but i have some weird behaviour.
When i play a video the images shakes a bit (like if u have trembling hands ). Even with the phone placed on the desk the images shakes. I don't really know why is happing that , do you know how to solve it? 

Thanks everyone.

**Comment by alesiaradkevich** [comment]
Hi! Can you please provide video and code samples that can help us reproduce this bug?
