### ISSUE TITLE
Not able to play any video after playing 1-3 videos.

### ISSUE THREAD

**Issue by Raj-commit** [flutterwtf/VR-Player#38]
Player is not able to play videos after some videos its just start buffering and does for every new video after that.
After reinstalling my app it does same -- Plays 1-3 videos and starts buffering again.
For smaller size videos upto 100mb i am able to play 4-8 times. But for large size video above 1gb i am able to play only 1-2 videos after that same buffering state for all videos
Why its happening and what can be the solution of it?

**Comment by alesiaradkevich** [comment]
Hi! Can you please provide video examples or code samples that can help us reproduce this bug?

**Comment by nsanchezpc** [comment]
Hi! I’m experiencing the same issue. After playing two times, the player starts buffering indefinitely.
Have you found any solution or workaround for this? Any insights would be really helpful.
